export { default as Lobby } from './Lobby.vue'
export { default as Cartas } from './Cartas.vue'
export { default as GanadoJuego } from './GanadoJuego.vue'
export { default as Login } from './Login.vue'
export { default as Register} from './Register.vue'
export { default as Home } from './Home.vue'
export { default as JoinGame} from './JoinGame.vue'
export { default as CreateGame} from './CreateGame.vue'
export{default as History} from  './History.vue'