export { default as TomarCarta } from './TomarCarta.vue'
export {default as Carta} from './Carta.vue'
export{ default as JoinGame} from './JoinGame.vue'
export { default as Cuadrados } from './Cuadrados.vue'
export { default as CentralCard} from './CentralCard.vue'
export {default as PlayerHand} from './PlayerHand.vue'